name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Configure SSH secret
        uses: shimataro/ssh-key-action@v2
        with:
          name: SSH_SECRET
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Update README
        run: node updateReadmeScript/update-readme-refactored.js

      - name: Commit changes
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          eval "$(ssh-agent -s)"
          ssh-add <(echo "$SSH_SECRET")
          git config --local user.email "pguilhermesantos@hotmail.com"
          git config --local user.name "pguilhermef"
          git add README.md
          git commit -m "Update README"
          git push
