name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Count consecutive days of commits
        id: count-commits
        run: |
          const fs = require('fs');
          const { execSync } = require('child_process');

          const commits = execSync('git log --format="%at"').toString().split('\n');

          let count = 0;
          let prevDate = null;

          for (const commit of commits) {
            if (!commit) continue;

            const date = new Date(Number(commit) * 1000).toISOString().substr(0, 10);

            if (prevDate !== date) {
              count++;
            } else {
              break;
            }

            prevDate = date;
          }

          console.log(`Consecutive days of commits: ${count}`);

          // Set the output variable for use in subsequent steps
          // This value can be accessed with ${{ steps.count-commits.outputs.count }}
          // in other steps
          echo "::set-output name=count::${count}"

      - name: Update README
        run: |
          # Read README template
          template=$(cat updateReadmeScript/README-template.md)

          # Replace {count} with the output from the previous step
          readme=$(echo "$template" | sed "s/{count}/${{ steps.count-commits.outputs.count }}/g")

          # Write the updated README
          echo "$readme" > README.md

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README with consecutive days of commits
          commit_options: '--no-verify'
          commit_user_email: pguilhermesantos@hotmail.com
          commit_user_name: pguilhermef
          branch: main
          file_pattern: README.md
