name: Update README

on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Update README
        run: node updateReadmeScript/update-readme.js

      - name: Commit changes
        run: |
          git config --local user.email "pguilhermesantos@hotmail.com"
          git config --local user.name "pguilhermef"
          git add README.md
          git commit -m "Update README"
          git push
