name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Git pull
        run: git pull

      - name: Install dependencies
        run: npm install

      - name: Update README
        run: node updateReadmeScript/update-readme.js

      - name: Commit changes
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          eval "$(ssh-agent -s)"
          ssh-add <(echo "$KEY")
          git config --local user.email "pguilhermesantos@hotmail.com"
          git config --local user.name "pguilhermef"
          git add README.md
          git commit -m "Update README"
          git push
